spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1/hero_dev?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8888
  servlet:
    context-path: /hero