spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1/hero_dev?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


server:
  port: 8888
  servlet:
    context-path: /hero

wechat:
  mpAppId: 123456789xxxxxxxxxxx
  mpAppSecret: 123456789xxxxxxxxxxx
  openAppId: 123456789xxxxxxxxxxx
  openAppSecret: 123456789xxxxxxxxxxx
  mchId: 123456789xxxxxxxxxxx
  mchKey: 123456789xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://hero.hero.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1/hero_dev?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


server:
  port: 8888
  servlet:
    context-path: /hero

wechat:
  mpAppId: 123456789xxxxxxxxxxx
  mpAppSecret: 123456789xxxxxxxxxxx
  openAppId: 123456789xxxxxxxxxxx
  openAppSecret: 123456789xxxxxxxxxxx
  mchId: 123456789xxxxxxxxxxx
  mchKey: 123456789xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://hero.hero.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
